Convert IP and MAC addresses into different formats
benoitc/inet_ext pull request #3
Opened 2018-09-05 01:21 UTC by vasu-dasari

2018-10-14 11:57 UTC, benoitc requested changes
can you remove the `sync` dependency? or maybe make it part of a dev profile if needed. But I don't think it's needed in prod. let me know :)

2018-10-14 11:57 UTC, benoitc commented on rebar.config
> +{deps, [
why this dependency?

2018-10-14 12:00 UTC, benoitc commented
i can also just make the change myself in a different commit. Just let me know what's your preference. Otherwise the patch looks good.

2018-10-15 13:31 UTC, vasu-dasari commented on rebar.config
> +{deps, [
Adding this dependecy makes it easy during development. Basically it scans for the files that have been modified and compiles those files and then hot-patches them on your running Erlang VM. That is a left over suring my development/debugging phase that should not have been included in a library like `inet_ext`. Will remove the dependency.

2018-10-15 14:00 UTC, benoitc approved these changes

2018-10-16 08:48 UTC, merged

2018-10-16 08:48 UTC, benoitc commented
thanks! merged

2018-10-16 14:10 UTC, vasu-dasari commented
> thanks! merged

Thanks @benoitc